# Generated by Django 6.1.1 on 2026-09-27 11:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

TABLES = ("mp_appointment", "mp_appointment_change")


def protect(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    from common.rls import get_enable_policy_sql

    with schema_editor.connection.cursor() as cursor:
        for table in TABLES:
            cursor.execute(get_enable_policy_sql(table))
        cursor.execute("""
            CREATE FUNCTION mp_validate_appointment_link() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                IF TG_TABLE_NAME = 'mp_appointment' THEN
                    IF NOT EXISTS (SELECT 1 FROM mp_patient WHERE id = NEW.patient_id AND org_id = NEW.org_id) THEN
                        RAISE EXCEPTION 'Appointment patient must belong to the same practice' USING ERRCODE = '23514';
                    END IF;
                    IF TG_OP = 'UPDATE' AND (NEW.org_id, NEW.patient_id, NEW.request_id) IS DISTINCT FROM (OLD.org_id, OLD.patient_id, OLD.request_id) THEN
                        RAISE EXCEPTION 'Appointment identity is immutable' USING ERRCODE = '23514';
                    END IF;
                ELSE
                    IF TG_OP <> 'INSERT' THEN
                        RAISE EXCEPTION 'Appointment history is append-only' USING ERRCODE = '23514';
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM mp_appointment WHERE id = NEW.appointment_id AND org_id = NEW.org_id) THEN
                        RAISE EXCEPTION 'Appointment history must belong to the same practice' USING ERRCODE = '23514';
                    END IF;
                    IF NEW.journey_event_id IS NOT NULL AND NOT EXISTS (
                        SELECT 1 FROM mp_journey_event e JOIN mp_appointment a ON a.patient_id = e.patient_id
                        WHERE a.id = NEW.appointment_id AND e.id = NEW.journey_event_id AND e.org_id = NEW.org_id
                    ) THEN
                        RAISE EXCEPTION 'Appointment event must belong to the same patient and practice' USING ERRCODE = '23514';
                    END IF;
                END IF;
                RETURN NEW;
            END $$;
            CREATE TRIGGER mp_appointment_link BEFORE INSERT OR UPDATE ON mp_appointment FOR EACH ROW EXECUTE FUNCTION mp_validate_appointment_link();
            CREATE TRIGGER mp_appointment_history BEFORE INSERT OR UPDATE OR DELETE ON mp_appointment_change FOR EACH ROW EXECUTE FUNCTION mp_validate_appointment_link();
        """)


def unprotect(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    from common.rls import get_disable_policy_sql

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "DROP TRIGGER IF EXISTS mp_appointment_history ON mp_appointment_change"
        )
        cursor.execute("DROP TRIGGER IF EXISTS mp_appointment_link ON mp_appointment")
        cursor.execute("DROP FUNCTION IF EXISTS mp_validate_appointment_link()")
        for table in TABLES:
            cursor.execute(get_disable_policy_sql(table))


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0043_org_help_center"),
        ("patients", "0002_rls_and_links"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("attended", "Attended"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "mp_appointment",
            },
        ),
        migrations.CreateModel(
            name="AppointmentChange",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("action", models.CharField(max_length=20)),
                ("reason", models.CharField(max_length=1000)),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="patients.appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "journey_event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.journeyevent",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "mp_appointment_change",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["org", "patient", "starts_at"],
                name="mp_appointm_org_id_df6873_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("org", "request_id"), name="mp_appointment_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="mp_appointment_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["scheduled", "attended", "cancelled", "no_show"])
                ),
                name="mp_appointment_status",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentchange",
            index=models.Index(
                fields=["org", "appointment", "created_at"],
                name="mp_appointm_org_id_d7fba2_idx",
            ),
        ),
        migrations.RunPython(protect, unprotect),
    ]
