# Generated by Django 6.1.1 on 2026-09-27 21:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def protect(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    from common.rls import get_enable_policy_sql

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("mp_payment_match"))
        cursor.execute("""
            CREATE FUNCTION mp_validate_payment_match() RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE facts record;
            BEGIN
                IF TG_OP <> 'INSERT' THEN
                    RAISE EXCEPTION 'Payment matches are append-only' USING ERRCODE = '23514';
                END IF;
                SELECT r.amount, r.reference, p.reference_number, p.payment_date, i.id AS invoice_id, i.contact_id, i.currency
                INTO facts
                FROM mp_receipt r JOIN mp_patient patient ON patient.id=r.patient_id
                JOIN payment p ON p.id=NEW.invoice_payment_id
                JOIN invoice i ON i.id=p.invoice_id
                WHERE r.id=NEW.receipt_id AND r.kind='payment' AND r.amount=p.amount
                AND r.org_id=NEW.org_id AND patient.org_id=NEW.org_id
                AND p.org_id=NEW.org_id AND i.org_id=NEW.org_id
                AND patient.contact_id=i.contact_id AND i.currency='USD'
                AND i.status NOT IN ('Draft','Pending','Cancelled');
                IF NOT FOUND THEN
                    RAISE EXCEPTION 'Match requires equal USD payments for the same patient and practice' USING ERRCODE = '23514';
                END IF;
                NEW.snapshot = jsonb_build_object(
                    'invoice',facts.invoice_id::text, 'contact',facts.contact_id::text,
                    'currency',facts.currency, 'amount',facts.amount::text,
                    'receipt_reference',facts.reference, 'payment_reference',facts.reference_number,
                    'payment_date',facts.payment_date::text
                );
                RETURN NEW;
            END $$;
            CREATE TRIGGER mp_payment_match_guard BEFORE INSERT OR UPDATE OR DELETE ON mp_payment_match
            FOR EACH ROW EXECUTE FUNCTION mp_validate_payment_match();
        """)


def unprotect(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    from common.rls import get_disable_policy_sql

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "DROP TRIGGER IF EXISTS mp_payment_match_guard ON mp_payment_match"
        )
        cursor.execute("DROP FUNCTION IF EXISTS mp_validate_payment_match()")
        cursor.execute(get_disable_policy_sql("mp_payment_match"))


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0043_org_help_center"),
        ("invoices", "0011_document_number_unique_per_org"),
        ("patients", "0003_appointments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMatch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("reason", models.CharField(max_length=1000)),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "invoice_payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_match",
                        to="invoices.payment",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_match",
                        to="patients.receipt",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "mp_payment_match",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.RunPython(protect, unprotect),
    ]
