# Generated by Django 6.1.1 on 2026-09-28 06:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def protect(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    from common.rls import get_enable_policy_sql

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("mp_payment_match_reversal"))
        cursor.execute("""
            CREATE OR REPLACE FUNCTION mp_validate_payment_match() RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE facts record;
            BEGIN
                IF TG_OP = 'UPDATE' AND OLD.active AND NOT NEW.active
                    AND (to_jsonb(NEW) - 'active') = (to_jsonb(OLD) - 'active')
                    AND EXISTS (SELECT 1 FROM mp_payment_match_reversal
                                WHERE match_id=OLD.id AND org_id=OLD.org_id) THEN
                    RETURN NEW;
                END IF;
                IF TG_OP <> 'INSERT' THEN
                    RAISE EXCEPTION 'Payment matches are append-only' USING ERRCODE = '23514';
                END IF;
                IF NOT NEW.active THEN
                    RAISE EXCEPTION 'New payment matches must be active' USING ERRCODE = '23514';
                END IF;
                SELECT r.amount, r.reference, p.reference_number, p.payment_date, i.id AS invoice_id, i.contact_id, i.currency
                INTO facts
                FROM mp_receipt r JOIN mp_patient patient ON patient.id=r.patient_id
                JOIN payment p ON p.id=NEW.invoice_payment_id
                JOIN invoice i ON i.id=p.invoice_id
                WHERE r.id=NEW.receipt_id AND r.kind='payment' AND r.amount=p.amount
                AND r.org_id=NEW.org_id AND patient.org_id=NEW.org_id
                AND p.org_id=NEW.org_id AND i.org_id=NEW.org_id
                AND patient.contact_id=i.contact_id AND i.currency='USD'
                AND i.status NOT IN ('Draft','Pending','Cancelled');
                IF NOT FOUND THEN
                    RAISE EXCEPTION 'Match requires equal USD payments for the same patient and practice' USING ERRCODE = '23514';
                END IF;
                NEW.snapshot = jsonb_build_object(
                    'invoice',facts.invoice_id::text, 'contact',facts.contact_id::text,
                    'currency',facts.currency, 'amount',facts.amount::text,
                    'receipt_reference',facts.reference, 'payment_reference',facts.reference_number,
                    'payment_date',facts.payment_date::text
                );
                RETURN NEW;
            END $$;

            CREATE FUNCTION mp_payment_match_reversal_guard() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                IF TG_OP <> 'INSERT' THEN
                    RAISE EXCEPTION 'Match reversals are append-only' USING ERRCODE = '23514';
                END IF;
                IF TG_WHEN = 'BEFORE' THEN
                    IF btrim(NEW.reason) = '' OR NEW.created_by_id IS NULL THEN
                        RAISE EXCEPTION 'Reversal requires a reason and actor' USING ERRCODE = '23514';
                    END IF;
                    PERFORM 1 FROM mp_payment_match
                        WHERE id=NEW.match_id AND org_id=NEW.org_id AND active FOR UPDATE;
                    IF NOT FOUND THEN
                        RAISE EXCEPTION 'Reversal requires an active match in this practice' USING ERRCODE = '23514';
                    END IF;
                ELSE
                    UPDATE mp_payment_match SET active=false WHERE id=NEW.match_id AND org_id=NEW.org_id;
                END IF;
                RETURN NEW;
            END $$;
            CREATE TRIGGER mp_match_reversal_guard BEFORE INSERT OR UPDATE OR DELETE ON mp_payment_match_reversal
                FOR EACH ROW EXECUTE FUNCTION mp_payment_match_reversal_guard();
            CREATE TRIGGER mp_match_reversal_release AFTER INSERT ON mp_payment_match_reversal
                FOR EACH ROW EXECUTE FUNCTION mp_payment_match_reversal_guard();
""")


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0043_org_help_center"),
        ("invoices", "0011_document_number_unique_per_org"),
        ("patients", "0004_payment_matches"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMatchReversal",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("reason", models.CharField(max_length=1000)),
            ],
            options={
                "db_table": "mp_payment_match_reversal",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="paymentmatch",
            name="active",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name="paymentmatch",
            name="invoice_payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patient_matches",
                to="invoices.payment",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmatch",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_matches",
                to="patients.receipt",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentmatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("receipt",),
                name="mp_active_receipt_match",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentmatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("invoice_payment",),
                name="mp_active_invoice_match",
            ),
        ),
        migrations.AddField(
            model_name="paymentmatchreversal",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="paymentmatchreversal",
            name="match",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal",
                to="patients.paymentmatch",
            ),
        ),
        migrations.AddField(
            model_name="paymentmatchreversal",
            name="org",
            field=models.ForeignKey(
                help_text="Organization this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="common.org",
            ),
        ),
        migrations.AddField(
            model_name="paymentmatchreversal",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        # Deliberately irreversible: dropping correction history is not a safe rollback.
        migrations.RunPython(protect),
    ]
