# Generated by Django 6.1.1 on 2026-10-04 06:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def protect(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    from common.rls import get_enable_policy_sql

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("mp_invoice_credit"))
        cursor.execute("""
            CREATE FUNCTION mp_invoice_credit_guard() RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE bill record; original record; used numeric; facts jsonb;
            BEGIN
                IF TG_OP <> 'INSERT' THEN
                    RAISE EXCEPTION 'Invoice credit history is append-only' USING ERRCODE = '23514';
                END IF;
                IF NEW.reason !~ '[^[:space:]]' OR NEW.created_by_id IS NULL THEN
                    RAISE EXCEPTION 'Credit requires a reason and actor' USING ERRCODE = '23514';
                END IF;
                SELECT * INTO bill FROM invoice WHERE id=NEW.invoice_id AND org_id=NEW.org_id FOR UPDATE;
                IF NOT FOUND OR NOT EXISTS(SELECT 1 FROM mp_patient WHERE id=NEW.patient_id AND org_id=NEW.org_id) THEN
                    RAISE EXCEPTION 'Credit links must belong to this practice' USING ERRCODE = '23514';
                END IF;
                IF NEW.reversal_of_id IS NOT NULL THEN
                    SELECT * INTO original FROM mp_invoice_credit
                        WHERE id=NEW.reversal_of_id AND org_id=NEW.org_id AND patient_id=NEW.patient_id
                        AND invoice_id=NEW.invoice_id AND reversal_of_id IS NULL FOR UPDATE;
                    IF NOT FOUND OR original.amount <> NEW.amount
                        OR EXISTS(SELECT 1 FROM mp_invoice_credit WHERE reversal_of_id=NEW.reversal_of_id) THEN
                        RAISE EXCEPTION 'Reverse one original credit in full, once' USING ERRCODE = '23514';
                    END IF;
                    NEW.snapshot = original.snapshot;
                    RETURN NEW;
                END IF;
                IF bill.currency <> 'USD' OR bill.status IN ('Draft','Pending','Cancelled')
                    OR NOT EXISTS(SELECT 1 FROM mp_patient WHERE id=NEW.patient_id AND contact_id=bill.contact_id) THEN
                    RAISE EXCEPTION 'Credit requires an issued USD invoice for this patient' USING ERRCODE = '23514';
                END IF;
                facts = jsonb_build_object('total',bill.total_amount::text, 'currency',bill.currency,
                    'contact',bill.contact_id::text, 'number',bill.invoice_number);
                SELECT COALESCE(sum(c.amount),0) INTO used FROM mp_invoice_credit c
                    WHERE c.invoice_id=NEW.invoice_id AND c.org_id=NEW.org_id AND c.reversal_of_id IS NULL
                    AND NOT EXISTS(SELECT 1 FROM mp_invoice_credit r WHERE r.reversal_of_id=c.id);
                IF NEW.amount + used > bill.total_amount THEN
                    RAISE EXCEPTION 'Credits cannot exceed invoice billed value' USING ERRCODE = '23514';
                END IF;
                IF EXISTS(SELECT 1 FROM mp_invoice_credit c WHERE c.invoice_id=NEW.invoice_id
                    AND c.org_id=NEW.org_id AND c.reversal_of_id IS NULL AND c.snapshot <> facts
                    AND NOT EXISTS(SELECT 1 FROM mp_invoice_credit r WHERE r.reversal_of_id=c.id)) THEN
                    RAISE EXCEPTION 'Reverse changed credits before adding another' USING ERRCODE = '23514';
                END IF;
                NEW.snapshot = facts;
                RETURN NEW;
            END $$;
            CREATE TRIGGER mp_invoice_credit_guard BEFORE INSERT OR UPDATE OR DELETE ON mp_invoice_credit
                FOR EACH ROW EXECUTE FUNCTION mp_invoice_credit_guard();
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0043_org_help_center"),
        ("invoices", "0011_document_number_unique_per_org"),
        ("patients", "0005_payment_match_reversals"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceCreditAdjustment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.CharField(max_length=1000)),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practice_credits",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_credits",
                        to="patients.patient",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="patients.invoicecreditadjustment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "mp_invoice_credit",
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="mp_invoice_credit_positive",
                    ),
                    models.UniqueConstraint(
                        fields=("org", "request_id"), name="mp_invoice_credit_request"
                    ),
                ],
            },
        ),
        # Dropping the audit history is not a safe rollback.
        migrations.RunPython(protect),
    ]
