# Generated by Django 6.1.1 on 2026-10-04 16:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def protect(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    from common.rls import get_enable_policy_sql

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("mp_receipt_allocation"))
        cursor.execute("""
        CREATE FUNCTION mp_allocation_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE cash record; bill record; person uuid; last_revision integer;
            line jsonb; total numeric := 0; refunded numeric; refund_rows jsonb;
            facts jsonb := '{}'::jsonb; seen uuid[] := '{}'; bill_id uuid;
        BEGIN
            IF TG_OP <> 'INSERT' THEN
                RAISE EXCEPTION 'Allocation history is append-only' USING ERRCODE='23514';
            END IF;
            IF NEW.reason !~ '[^[:space:]]' OR NEW.created_by_id IS NULL THEN
                RAISE EXCEPTION 'Allocation requires a reason and actor' USING ERRCODE='23514';
            END IF;
            SELECT * INTO cash FROM mp_receipt WHERE id=NEW.receipt_id AND org_id=NEW.org_id
                AND patient_id=NEW.patient_id AND kind='payment' FOR UPDATE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'Allocation receipt must belong to this patient and practice' USING ERRCODE='23514';
            END IF;
            SELECT contact_id INTO person FROM mp_patient WHERE id=NEW.patient_id AND org_id=NEW.org_id;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'Allocation patient must belong to this practice' USING ERRCODE='23514';
            END IF;
            SELECT COALESCE(max(revision),0) INTO last_revision FROM mp_receipt_allocation WHERE receipt_id=NEW.receipt_id AND org_id=NEW.org_id;
            IF NEW.revision <> last_revision + 1 THEN
                RAISE EXCEPTION 'Allocation revision is stale' USING ERRCODE='23514';
            END IF;
            IF jsonb_typeof(NEW.lines) <> 'array' OR jsonb_array_length(NEW.lines)>20 THEN
                RAISE EXCEPTION 'Use up to 20 allocation lines' USING ERRCODE='23514';
            END IF;
            FOR line IN SELECT value FROM jsonb_array_elements(NEW.lines) ORDER BY value->>'invoice' LOOP
                IF jsonb_typeof(line) <> 'object' OR NOT (line ?& ARRAY['invoice','amount']) THEN
                    RAISE EXCEPTION 'Allocation line requires invoice and amount' USING ERRCODE='23514';
                END IF;
                IF (SELECT count(*) FROM jsonb_object_keys(line)) <> 2
                    OR jsonb_typeof(line->'invoice') <> 'string' OR jsonb_typeof(line->'amount') <> 'string'
                    OR (line->>'invoice') !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
                    OR (line->>'amount') !~ '^[0-9]{1,10}[.][0-9]{2}$' THEN
                    RAISE EXCEPTION 'Invalid allocation line' USING ERRCODE='23514';
                END IF;
                bill_id := (line->>'invoice')::uuid;
                IF bill_id=ANY(seen) OR (line->>'amount')::numeric <= 0 THEN
                    RAISE EXCEPTION 'Use positive amounts and unique invoices' USING ERRCODE='23514';
                END IF;
                seen := array_append(seen,bill_id);
                SELECT * INTO bill FROM invoice WHERE id=bill_id AND org_id=NEW.org_id
                    AND contact_id=person AND currency='USD' AND status NOT IN ('Draft','Pending','Cancelled') FOR UPDATE;
                IF NOT FOUND THEN
                    RAISE EXCEPTION 'Allocation invoice must be issued USD for this patient and practice' USING ERRCODE='23514';
                END IF;
                total := total + (line->>'amount')::numeric;
                facts := facts || jsonb_build_object(bill_id::text,jsonb_build_object('total',bill.total_amount::text,'currency',bill.currency,'contact',bill.contact_id::text,'number',bill.invoice_number));
            END LOOP;
            SELECT COALESCE(sum(amount),0), COALESCE(jsonb_agg(jsonb_build_object('id',id::text,'amount',amount::text) ORDER BY id),'[]'::jsonb)
                INTO refunded,refund_rows FROM mp_receipt WHERE org_id=NEW.org_id AND payment_id=NEW.receipt_id AND kind='refund';
            IF total > cash.amount-refunded THEN
                RAISE EXCEPTION 'Allocation exceeds net receipt cash' USING ERRCODE='23514';
            END IF;
            NEW.snapshot := jsonb_build_object('receipt',jsonb_build_object('amount',cash.amount::text,'reference',cash.reference,
                'patient',cash.patient_id::text,'contact',person::text,'kind',cash.kind,'net',(cash.amount-refunded)::text,'refunds',refund_rows),'invoices',facts);
            RETURN NEW;
        END $$;
        CREATE TRIGGER mp_allocation_guard BEFORE INSERT OR UPDATE OR DELETE ON mp_receipt_allocation
            FOR EACH ROW EXECUTE FUNCTION mp_allocation_guard();
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0043_org_help_center"),
        ("patients", "0006_invoice_credit_adjustments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptAllocation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("request_id", models.UUIDField()),
                ("reason", models.CharField(max_length=1000)),
                ("lines", models.JSONField(default=list)),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patient",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.receipt",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "mp_receipt_allocation",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "request_id"), name="mp_allocation_request"
                    ),
                    models.UniqueConstraint(
                        fields=("receipt", "revision"), name="mp_allocation_revision"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision__gt", 0)),
                        name="mp_allocation_revision_positive",
                    ),
                ],
            },
        ),
        migrations.RunPython(protect),  # Audit history must not be erased by rollback.
    ]
