# Generated by Django 6.1.1 on 2026-10-04 21:18

from django.db import migrations, models


def protect(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
        CREATE OR REPLACE FUNCTION mp_allocation_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE cash record; bill record; person uuid; last_revision integer;
            line jsonb; total numeric := 0; refunded numeric; refund_rows jsonb;
            facts jsonb := '{}'::jsonb; seen text[] := '{}'; bill_id uuid;
            refund_id uuid; refund_amount numeric; used numeric; refund_used jsonb := '{}'::jsonb;
            pair_key text; is_refund boolean;
        BEGIN
            IF TG_OP <> 'INSERT' THEN
                RAISE EXCEPTION 'Allocation history is append-only' USING ERRCODE='23514';
            END IF;
            IF NEW.reason !~ '[^[:space:]]' OR NEW.created_by_id IS NULL THEN
                RAISE EXCEPTION 'Allocation requires a reason and actor' USING ERRCODE='23514';
            END IF;
            SELECT * INTO cash FROM mp_receipt WHERE id=NEW.receipt_id AND org_id=NEW.org_id
                AND patient_id=NEW.patient_id AND kind='payment' FOR UPDATE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'Allocation receipt must belong to this patient and practice' USING ERRCODE='23514';
            END IF;
            SELECT contact_id INTO person FROM mp_patient WHERE id=NEW.patient_id AND org_id=NEW.org_id;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'Allocation patient must belong to this practice' USING ERRCODE='23514';
            END IF;
            SELECT COALESCE(max(revision),0) INTO last_revision FROM mp_receipt_allocation WHERE receipt_id=NEW.receipt_id AND org_id=NEW.org_id;
            IF NEW.revision <> last_revision + 1 THEN
                RAISE EXCEPTION 'Allocation revision is stale' USING ERRCODE='23514';
            END IF;
            IF jsonb_typeof(NEW.lines) <> 'array' OR jsonb_typeof(NEW.refund_lines) <> 'array' THEN
                RAISE EXCEPTION 'Use allocation arrays' USING ERRCODE='23514';
            END IF;
            IF jsonb_array_length(NEW.lines)>20 OR jsonb_array_length(NEW.refund_lines)>100
                OR EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.lines) x WHERE x ? 'refund')
                OR EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.refund_lines) x WHERE NOT (x ? 'refund')) THEN
                RAISE EXCEPTION 'Invalid allocation line groups' USING ERRCODE='23514';
            END IF;
            FOR line IN SELECT value FROM jsonb_array_elements(NEW.lines || NEW.refund_lines) ORDER BY value->>'invoice' LOOP
                is_refund := line ? 'refund';
                IF jsonb_typeof(line) <> 'object' OR NOT (line ?& ARRAY['invoice','amount']) THEN
                    RAISE EXCEPTION 'Allocation requires invoice and amount' USING ERRCODE='23514';
                END IF;
                IF (SELECT count(*) FROM jsonb_object_keys(line)) <> (CASE WHEN is_refund THEN 3 ELSE 2 END)
                    OR jsonb_typeof(line->'amount') <> 'string'
                    OR (line->>'amount') !~ '^[0-9]{1,10}[.][0-9]{2}$'
                    OR (line->>'amount')::numeric <= 0 THEN
                    RAISE EXCEPTION 'Invalid allocation amount or fields' USING ERRCODE='23514';
                END IF;
                IF NOT (is_refund AND line->'invoice' = 'null'::jsonb) THEN
                    IF jsonb_typeof(line->'invoice') <> 'string'
                        OR (line->>'invoice') !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN
                        RAISE EXCEPTION 'Invalid allocation invoice' USING ERRCODE='23514';
                    END IF;
                    bill_id := (line->>'invoice')::uuid;
                    SELECT * INTO bill FROM invoice WHERE id=bill_id AND org_id=NEW.org_id
                        AND contact_id=person AND currency='USD' AND status NOT IN ('Draft','Pending','Cancelled') FOR UPDATE;
                    IF NOT FOUND THEN
                        RAISE EXCEPTION 'Allocation invoice must be issued USD for this patient and practice' USING ERRCODE='23514';
                    END IF;
                    facts := facts || jsonb_build_object(bill_id::text,jsonb_build_object('total',bill.total_amount::text,'currency',bill.currency,'contact',bill.contact_id::text,'number',bill.invoice_number));
                END IF;
                IF is_refund THEN
                    IF jsonb_typeof(line->'refund') <> 'string'
                        OR (line->>'refund') !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN
                        RAISE EXCEPTION 'Invalid refund identifier' USING ERRCODE='23514';
                    END IF;
                    refund_id := (line->>'refund')::uuid;
                    SELECT amount INTO refund_amount FROM mp_receipt WHERE id=refund_id AND org_id=NEW.org_id
                        AND patient_id=NEW.patient_id AND payment_id=NEW.receipt_id AND kind='refund';
                    IF NOT FOUND THEN
                        RAISE EXCEPTION 'Refund must belong to this receipt, patient and practice' USING ERRCODE='23514';
                    END IF;
                    used := COALESCE((refund_used->>refund_id::text)::numeric,0) + (line->>'amount')::numeric;
                    IF used > refund_amount THEN
                        RAISE EXCEPTION 'Refund allocation exceeds recorded refund' USING ERRCODE='23514';
                    END IF;
                    refund_used := refund_used || jsonb_build_object(refund_id::text,used);
                    pair_key := refund_id::text || ':' || COALESCE(line->>'invoice','unallocated');
                ELSE
                    total := total + (line->>'amount')::numeric;
                    pair_key := 'net:' || (line->>'invoice');
                END IF;
                IF pair_key=ANY(seen) THEN
                    RAISE EXCEPTION 'Duplicate allocation line' USING ERRCODE='23514';
                END IF;
                seen := array_append(seen,pair_key);
            END LOOP;
            SELECT COALESCE(sum(amount),0), COALESCE(jsonb_agg(jsonb_build_object('id',id::text,'amount',amount::text) ORDER BY id),'[]'::jsonb)
                INTO refunded,refund_rows FROM mp_receipt WHERE org_id=NEW.org_id AND payment_id=NEW.receipt_id AND kind='refund';
            IF total > cash.amount-refunded THEN
                RAISE EXCEPTION 'Allocation exceeds net receipt cash' USING ERRCODE='23514';
            END IF;
            NEW.snapshot := jsonb_build_object('receipt',jsonb_build_object('amount',cash.amount::text,'reference',cash.reference,
                'patient',cash.patient_id::text,'contact',person::text,'kind',cash.kind,'net',(cash.amount-refunded)::text,'refunds',refund_rows),'invoices',facts);
            RETURN NEW;
        END $$;
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0007_receipt_allocations"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptallocation",
            name="refund_lines",
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(protect),  # Preserve refund audit history on rollback.
    ]
