# Generated by Django 6.1.1 on 2026-10-08 15:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def protect(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    from common.rls import get_enable_policy_sql

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("mp_receipt_correction"))
        cursor.execute("""
        CREATE FUNCTION mp_correction_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE cash record; parent_id uuid; last_revision integer; plan record;
        BEGIN
            IF TG_OP <> 'INSERT' THEN
                RAISE EXCEPTION 'Cash correction history is append-only' USING ERRCODE='23514';
            END IF;
            IF NEW.created_by_id IS NULL OR NEW.reason !~ '[^[:space:]]' THEN
                RAISE EXCEPTION 'Correction requires an actor and reason' USING ERRCODE='23514';
            END IF;
            SELECT COALESCE(payment_id,id) INTO parent_id FROM mp_receipt
                WHERE id=NEW.receipt_id AND org_id=NEW.org_id AND patient_id=NEW.patient_id;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'Correction receipt must belong to this patient and practice' USING ERRCODE='23514';
            END IF;
            PERFORM 1 FROM mp_receipt WHERE id=parent_id AND org_id=NEW.org_id
                AND patient_id=NEW.patient_id AND kind='payment' FOR UPDATE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'Correction payment must belong to this patient and practice' USING ERRCODE='23514';
            END IF;
            SELECT * INTO cash FROM mp_receipt WHERE id=NEW.receipt_id AND org_id=NEW.org_id FOR UPDATE;
            SELECT COALESCE(max(revision),0) INTO last_revision FROM mp_receipt_correction
                WHERE receipt_id=NEW.receipt_id AND org_id=NEW.org_id;
            IF NEW.revision <> last_revision+1 OR NEW.amount=cash.amount THEN
                RAISE EXCEPTION 'Correction revision is stale or amount is unchanged' USING ERRCODE='23514';
            END IF;
            IF EXISTS(SELECT 1 FROM mp_payment_match WHERE receipt_id=parent_id AND org_id=NEW.org_id AND active) THEN
                RAISE EXCEPTION 'Reverse the active match before correcting cash' USING ERRCODE='23514';
            END IF;
            SELECT * INTO plan FROM mp_receipt_allocation WHERE receipt_id=parent_id AND org_id=NEW.org_id ORDER BY revision DESC LIMIT 1;
            IF FOUND AND (plan.lines<>'[]'::jsonb OR plan.refund_lines<>'[]'::jsonb) THEN
                RAISE EXCEPTION 'Clear allocations before correcting cash' USING ERRCODE='23514';
            END IF;
            NEW.snapshot := to_jsonb(cash);
            RETURN NEW;
        END $$;
        CREATE TRIGGER mp_correction_guard BEFORE INSERT OR UPDATE OR DELETE ON mp_receipt_correction
            FOR EACH ROW EXECUTE FUNCTION mp_correction_guard();

        CREATE FUNCTION mp_correction_apply() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            UPDATE mp_receipt SET amount=NEW.amount, updated_at=NEW.created_at, updated_by_id=NEW.created_by_id
                WHERE id=NEW.receipt_id AND org_id=NEW.org_id;
            RETURN NEW;
        END $$;
        CREATE TRIGGER mp_correction_apply AFTER INSERT ON mp_receipt_correction
            FOR EACH ROW EXECUTE FUNCTION mp_correction_apply();

        CREATE FUNCTION mp_receipt_audit_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP='DELETE' THEN
                RAISE EXCEPTION 'Cash records cannot be deleted' USING ERRCODE='23514';
            END IF;
            IF (NEW.id,NEW.org_id,NEW.patient_id,NEW.kind,NEW.payment_id,NEW.reference,NEW.occurred_at,NEW.notes,NEW.created_at,NEW.created_by_id)
                IS DISTINCT FROM
                (OLD.id,OLD.org_id,OLD.patient_id,OLD.kind,OLD.payment_id,OLD.reference,OLD.occurred_at,OLD.notes,OLD.created_at,OLD.created_by_id) THEN
                RAISE EXCEPTION 'Original cash identity and recorded details are immutable' USING ERRCODE='23514';
            END IF;
            IF NEW.amount<>OLD.amount AND (pg_trigger_depth()<2 OR NOT EXISTS(
                SELECT 1 FROM mp_receipt_correction WHERE receipt_id=NEW.id AND org_id=NEW.org_id
                    AND amount=NEW.amount AND (snapshot->>'amount')::numeric=OLD.amount
                    AND created_by_id=NEW.updated_by_id AND created_at=NEW.updated_at
            )) THEN
                RAISE EXCEPTION 'Amount changes require audited cash correction' USING ERRCODE='23514';
            END IF;
            RETURN NEW;
        END $$;
        -- Run existing refund/tenant checks first, preserving their specific errors.
        CREATE TRIGGER mp_receipt_z_audit_guard BEFORE UPDATE OR DELETE ON mp_receipt
            FOR EACH ROW EXECUTE FUNCTION mp_receipt_audit_guard();
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0043_org_help_center"),
        ("patients", "0009_receipt_refund_guard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptCorrection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("request_id", models.UUIDField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.CharField(max_length=1000)),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patient",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.receipt",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "mp_receipt_correction",
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "request_id"), name="mp_cash_correction_request"
                    ),
                    models.UniqueConstraint(
                        fields=("receipt", "revision"),
                        name="mp_cash_correction_revision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="mp_cash_correction_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision__gt", 0)),
                        name="mp_cash_correction_revision_positive",
                    ),
                ],
            },
        ),
        migrations.RunPython(protect),  # Audit history must not be erased by rollback.
    ]
