# Generated by Django 6.1.1 on 2026-10-08 16:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def protect(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    from common.rls import get_enable_policy_sql

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("mp_receipt_exclusion"))
        cursor.execute("""
        CREATE FUNCTION mp_exclusion_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE cash record; kept record; plan record; n integer; item uuid;
        BEGIN
            IF TG_OP <> 'INSERT' THEN
                RAISE EXCEPTION 'Exclusion history is append-only' USING ERRCODE='23514';
            END IF;
            IF NEW.created_by_id IS NULL OR NEW.reason !~ '[^[:space:]]' THEN
                RAISE EXCEPTION 'Exclusion requires actor and reason' USING ERRCODE='23514';
            END IF;
            -- Stable write-lock order also rejects stale repeatable-read snapshots.
            FOR item IN SELECT id FROM mp_receipt WHERE id IN (NEW.receipt_id,NEW.retained_id)
                AND org_id=NEW.org_id AND patient_id=NEW.patient_id ORDER BY id LOOP
                UPDATE mp_receipt SET amount=amount WHERE id=item AND org_id=NEW.org_id;
            END LOOP;
            SELECT * INTO cash FROM mp_receipt WHERE id=NEW.receipt_id AND org_id=NEW.org_id
                AND patient_id=NEW.patient_id AND kind='payment';
            IF NOT FOUND THEN
                RAISE EXCEPTION 'Exclusion payment must belong to this patient and practice' USING ERRCODE='23514';
            END IF;
            SELECT COALESCE(max(revision),0) INTO n FROM mp_receipt_exclusion WHERE receipt_id=cash.id AND org_id=NEW.org_id;
            IF NEW.revision<>n+1 OR NEW.excluded=cash.excluded THEN
                RAISE EXCEPTION 'Stale exclusion revision or unchanged status' USING ERRCODE='23514';
            END IF;
            NEW.snapshot := jsonb_build_object('receipt',to_jsonb(cash));
            IF NEW.excluded THEN
                SELECT * INTO kept FROM mp_receipt WHERE id=NEW.retained_id AND org_id=NEW.org_id
                    AND patient_id=NEW.patient_id AND kind='payment' AND NOT excluded
                    AND id<>cash.id AND amount=cash.amount;
                IF NOT FOUND THEN
                    RAISE EXCEPTION 'Retain a different active equal-amount payment for this patient' USING ERRCODE='23514';
                END IF;
                IF EXISTS(SELECT 1 FROM mp_receipt WHERE payment_id=cash.id AND org_id=NEW.org_id) THEN
                    RAISE EXCEPTION 'Payments with refunds cannot be excluded' USING ERRCODE='23514';
                END IF;
                IF EXISTS(SELECT 1 FROM mp_payment_match WHERE receipt_id=cash.id AND org_id=NEW.org_id AND active) THEN
                    RAISE EXCEPTION 'Reverse the payment match before exclusion' USING ERRCODE='23514';
                END IF;
                SELECT * INTO plan FROM mp_receipt_allocation WHERE receipt_id=cash.id AND org_id=NEW.org_id ORDER BY revision DESC LIMIT 1;
                IF FOUND AND (plan.lines<>'[]'::jsonb OR plan.refund_lines<>'[]'::jsonb) THEN
                    RAISE EXCEPTION 'Clear allocation before exclusion' USING ERRCODE='23514';
                END IF;
                IF EXISTS(SELECT 1 FROM mp_receipt_exclusion e JOIN mp_receipt r ON r.id=e.receipt_id
                    WHERE e.retained_id=cash.id AND e.org_id=NEW.org_id AND r.excluded
                    AND e.revision=(SELECT max(revision) FROM mp_receipt_exclusion WHERE receipt_id=r.id AND org_id=NEW.org_id)) THEN
                    RAISE EXCEPTION 'Another excluded payment relies on this retained payment; restore it first' USING ERRCODE='23514';
                END IF;
                NEW.snapshot := NEW.snapshot || jsonb_build_object('retained',to_jsonb(kept));
            ELSIF NEW.retained_id IS NOT NULL THEN
                RAISE EXCEPTION 'Restoration must not select a retained payment' USING ERRCODE='23514';
            END IF;
            RETURN NEW;
        END $$;
        CREATE TRIGGER mp_exclusion_guard BEFORE INSERT OR UPDATE OR DELETE ON mp_receipt_exclusion
            FOR EACH ROW EXECUTE FUNCTION mp_exclusion_guard();
        CREATE FUNCTION mp_exclusion_apply() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            UPDATE mp_receipt SET excluded=NEW.excluded, updated_at=NEW.created_at, updated_by_id=NEW.created_by_id
                WHERE id=NEW.receipt_id AND org_id=NEW.org_id;
            RETURN NEW;
        END $$;
        CREATE TRIGGER mp_exclusion_apply AFTER INSERT ON mp_receipt_exclusion
            FOR EACH ROW EXECUTE FUNCTION mp_exclusion_apply();

        CREATE FUNCTION mp_excluded_receipt_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP='INSERT' AND NEW.excluded THEN
                RAISE EXCEPTION 'New cash must be included' USING ERRCODE='23514';
            END IF;
            IF TG_OP='UPDATE' AND NEW.excluded IS DISTINCT FROM OLD.excluded AND
                (pg_trigger_depth()<2 OR NOT EXISTS(SELECT 1 FROM mp_receipt_exclusion e
                    WHERE e.receipt_id=NEW.id AND e.org_id=NEW.org_id AND e.excluded=NEW.excluded
                    AND e.created_at=NEW.updated_at AND e.created_by_id=NEW.updated_by_id
                    AND e.revision=(SELECT max(revision) FROM mp_receipt_exclusion WHERE receipt_id=NEW.id AND org_id=NEW.org_id))) THEN
                RAISE EXCEPTION 'Status changes require audited exclusion or restoration' USING ERRCODE='23514';
            END IF;
            IF NEW.kind='refund' AND EXISTS(SELECT 1 FROM mp_receipt WHERE id=NEW.payment_id AND org_id=NEW.org_id AND excluded) THEN
                RAISE EXCEPTION 'Excluded payments cannot receive refunds' USING ERRCODE='23514';
            END IF;
            RETURN NEW;
        END $$;
        -- Refund budget trigger has already write-locked the parent.
        CREATE TRIGGER mp_receipt_zz_excluded BEFORE INSERT OR UPDATE ON mp_receipt
            FOR EACH ROW EXECUTE FUNCTION mp_excluded_receipt_guard();

        CREATE FUNCTION mp_require_included_cash() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE cash record;
        BEGIN
            UPDATE mp_receipt SET amount=amount WHERE id=NEW.receipt_id AND org_id=NEW.org_id RETURNING * INTO cash;
            IF NOT FOUND OR cash.excluded THEN
                RAISE EXCEPTION 'Restore excluded cash before matching, allocating or correcting it' USING ERRCODE='23514';
            END IF;
            RETURN NEW;
        END $$;
        CREATE TRIGGER mp_aa_included BEFORE INSERT ON mp_payment_match FOR EACH ROW EXECUTE FUNCTION mp_require_included_cash();
        CREATE TRIGGER mp_aa_included BEFORE INSERT ON mp_receipt_allocation FOR EACH ROW EXECUTE FUNCTION mp_require_included_cash();
        CREATE TRIGGER mp_aa_included BEFORE INSERT ON mp_receipt_correction FOR EACH ROW EXECUTE FUNCTION mp_require_included_cash();
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0043_org_help_center"),
        ("patients", "0010_receipt_corrections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="excluded",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name="ReceiptExclusion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("excluded", models.BooleanField()),
                ("revision", models.PositiveIntegerField()),
                ("request_id", models.UUIDField()),
                ("reason", models.CharField(max_length=1000)),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patient",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exclusions",
                        to="patients.receipt",
                    ),
                ),
                (
                    "retained",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duplicate_decisions",
                        to="patients.receipt",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "mp_receipt_exclusion",
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "request_id"), name="mp_exclusion_request"
                    ),
                    models.UniqueConstraint(
                        fields=("receipt", "revision"), name="mp_exclusion_revision"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision__gt", 0)),
                        name="mp_exclusion_revision_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("excluded", True), ("retained__isnull", False)),
                            models.Q(("excluded", False), ("retained__isnull", True)),
                            _connector="OR",
                        ),
                        name="mp_exclusion_retained",
                    ),
                ],
            },
        ),
        migrations.RunPython(protect),
    ]
