# Generated by Django 6.1.1 on 2026-10-11 04:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def protect(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    from common.rls import get_enable_policy_sql

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("mp_cash_reference_reservation"))
        cursor.execute("""
        CREATE OR REPLACE FUNCTION mp_correction_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE cash record; parent_id uuid; last_revision integer; plan record;
        BEGIN
            IF TG_OP <> 'INSERT' THEN
                RAISE EXCEPTION 'Cash correction history is append-only' USING ERRCODE='23514';
            END IF;
            IF NEW.created_by_id IS NULL OR NEW.reason !~ '[^[:space:]]' THEN
                RAISE EXCEPTION 'Correction requires an actor and reason' USING ERRCODE='23514';
            END IF;
            SELECT COALESCE(payment_id,id) INTO parent_id FROM mp_receipt
                WHERE id=NEW.receipt_id AND org_id=NEW.org_id AND patient_id=NEW.patient_id;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'Correction receipt must belong to this patient and practice' USING ERRCODE='23514';
            END IF;
            PERFORM 1 FROM mp_receipt WHERE id=parent_id AND org_id=NEW.org_id
                AND patient_id=NEW.patient_id AND kind='payment' FOR UPDATE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'Correction payment must belong to this patient and practice' USING ERRCODE='23514';
            END IF;
            SELECT * INTO cash FROM mp_receipt WHERE id=NEW.receipt_id AND org_id=NEW.org_id FOR UPDATE;
            SELECT COALESCE(max(revision),0) INTO last_revision FROM mp_receipt_correction
                WHERE receipt_id=NEW.receipt_id AND org_id=NEW.org_id;
            IF NEW.revision <> last_revision+1
                OR (NEW.reference IS NULL AND NEW.amount=cash.amount)
                OR (NEW.reference IS NOT NULL AND (NEW.amount<>cash.amount OR NEW.reference=cash.reference OR NEW.reference !~ '[^[:space:]]' OR NEW.reference<>btrim(NEW.reference))) THEN
                RAISE EXCEPTION 'Stale revision, unchanged value or invalid combined correction' USING ERRCODE='23514';
            END IF;
            IF EXISTS(SELECT 1 FROM mp_payment_match WHERE receipt_id=parent_id AND org_id=NEW.org_id AND active) THEN
                RAISE EXCEPTION 'Reverse the active match before correcting cash' USING ERRCODE='23514';
            END IF;
            SELECT * INTO plan FROM mp_receipt_allocation WHERE receipt_id=parent_id AND org_id=NEW.org_id ORDER BY revision DESC LIMIT 1;
            IF FOUND AND (plan.lines<>'[]'::jsonb OR plan.refund_lines<>'[]'::jsonb) THEN
                RAISE EXCEPTION 'Clear allocations before correcting cash' USING ERRCODE='23514';
            END IF;
            NEW.snapshot := to_jsonb(cash);
            RETURN NEW;
        END $$;
        CREATE OR REPLACE FUNCTION mp_correction_apply() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            UPDATE mp_receipt SET amount=NEW.amount, reference=COALESCE(NEW.reference, reference), updated_at=NEW.created_at, updated_by_id=NEW.created_by_id
                WHERE id=NEW.receipt_id AND org_id=NEW.org_id;
            RETURN NEW;
        END $$;
        CREATE OR REPLACE FUNCTION mp_receipt_audit_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP='DELETE' THEN
                RAISE EXCEPTION 'Cash records cannot be deleted' USING ERRCODE='23514';
            END IF;
            IF (NEW.id,NEW.org_id,NEW.patient_id,NEW.kind,NEW.payment_id,NEW.occurred_at,NEW.notes,NEW.created_at,NEW.created_by_id)
                IS DISTINCT FROM
                (OLD.id,OLD.org_id,OLD.patient_id,OLD.kind,OLD.payment_id,OLD.occurred_at,OLD.notes,OLD.created_at,OLD.created_by_id) THEN
                RAISE EXCEPTION 'Original cash identity and recorded details are immutable' USING ERRCODE='23514';
            END IF;
            IF NEW.reference<>OLD.reference AND (pg_trigger_depth()<2 OR NOT EXISTS(
                SELECT 1 FROM mp_receipt_correction WHERE receipt_id=NEW.id AND org_id=NEW.org_id
                    AND reference=NEW.reference AND snapshot->>'reference'=OLD.reference
                    AND amount=OLD.amount AND NEW.amount=OLD.amount
                    AND created_by_id=NEW.updated_by_id AND created_at=NEW.updated_at
                    AND revision=(SELECT max(revision) FROM mp_receipt_correction WHERE receipt_id=NEW.id AND org_id=NEW.org_id)
            )) THEN
                RAISE EXCEPTION 'Original cash reference is immutable outside audited correction' USING ERRCODE='23514';
            END IF;
            IF NEW.amount<>OLD.amount AND (pg_trigger_depth()<2 OR NOT EXISTS(
                SELECT 1 FROM mp_receipt_correction WHERE receipt_id=NEW.id AND org_id=NEW.org_id
                    AND amount=NEW.amount AND (snapshot->>'amount')::numeric=OLD.amount
                    AND created_by_id=NEW.updated_by_id AND created_at=NEW.updated_at
            )) THEN
                RAISE EXCEPTION 'Amount changes require audited cash correction' USING ERRCODE='23514';
            END IF;
            RETURN NEW;
        END $$;
        CREATE FUNCTION mp_reference_history_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP<>'INSERT' OR pg_trigger_depth()<2 THEN
                RAISE EXCEPTION 'Receipt reference reservations are immutable and trigger-managed' USING ERRCODE='23514';
            END IF;
            RETURN NEW;
        END $$;
        CREATE TRIGGER mp_reference_history_guard BEFORE INSERT OR UPDATE OR DELETE ON mp_cash_reference_reservation
            FOR EACH ROW EXECUTE FUNCTION mp_reference_history_guard();

        CREATE FUNCTION mp_reserve_receipt_reference() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE key text; keys text[];
        BEGIN
            IF TG_OP='UPDATE' THEN
                IF NEW.reference=OLD.reference THEN RETURN NEW; END IF;
                keys:=ARRAY[OLD.reference,NEW.reference];
            ELSE
                keys:=ARRAY[NEW.reference];
            END IF;
            -- Reserve old and new references atomically. Uniqueness also serializes
            -- competing writers under repeatable-read snapshots. Stable key order.
            FOR key IN SELECT DISTINCT x FROM unnest(keys) x ORDER BY x LOOP
                INSERT INTO mp_cash_reference_reservation (id,org_id,receipt_id,reference,created_at,updated_at)
                    VALUES (gen_random_uuid(),NEW.org_id,NEW.id,key,now(),now())
                    ON CONFLICT (org_id,reference) DO NOTHING;
                IF NOT EXISTS(SELECT 1 FROM mp_cash_reference_reservation
                    WHERE org_id=NEW.org_id AND reference=key AND receipt_id=NEW.id) THEN
                    RAISE EXCEPTION 'Reference is reserved by another cash record in this practice' USING ERRCODE='23514';
                END IF;
            END LOOP;
            RETURN NEW;
        END $$;
        -- After identity validation. Existing rows are reserved lazily on first
        -- reference correction; current-reference uniqueness protects legacy keys.
        CREATE TRIGGER mp_receipt_zzz_reference BEFORE INSERT OR UPDATE ON mp_receipt
            FOR EACH ROW EXECUTE FUNCTION mp_reserve_receipt_reference();
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0043_org_help_center"),
        ("patients", "0011_receipt_exclusions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptcorrection",
            name="reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="ReceiptReference",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("reference", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.receipt",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "mp_cash_reference_reservation",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "reference"), name="mp_reserved_cash_reference"
                    )
                ],
            },
        ),
        migrations.RunPython(protect),
    ]
