# Generated by Django 6.0.7 on 2026-08-17 01:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql

# Registered in common/rls/__init__.py:ORG_SCOPED_TABLES. Kept in one list here
# so the enable and disable directions cannot drift apart.
WEBFORM_TABLES = [
    "web_form",
    "web_form_field",
    "web_form_submission",
    "web_form_daily_stat",
]


def enable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        for table in WEBFORM_TABLES:
            cursor.execute(get_enable_policy_sql(table))


def disable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        for table in WEBFORM_TABLES:
            cursor.execute(get_disable_policy_sql(table))


class Migration(migrations.Migration):
    initial = True

    # RLS policy creation cannot run inside an atomic block.
    atomic = False

    dependencies = [
        ("common", "0040_comment_max_length"),
        ("leads", "0016_alter_leadpipeline_is_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebForm",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Only published forms accept submissions. Flipped through the publish and unpublish endpoints, never through a plain update.",
                    ),
                ),
                (
                    "allowed_origins",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Origins permitted to frame this form or POST to it. An empty list means unrestricted.",
                    ),
                ),
                (
                    "submit_button_label",
                    models.CharField(default="Submit", max_length=64),
                ),
                (
                    "success_mode",
                    models.CharField(
                        choices=[
                            ("message", "Show a message"),
                            ("redirect", "Redirect to a URL"),
                        ],
                        default="message",
                        max_length=16,
                    ),
                ),
                (
                    "success_message",
                    models.TextField(
                        blank=True, default="Thanks. We will be in touch shortly."
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "lead_source",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("email", "Email"),
                            ("existing customer", "Existing Customer"),
                            ("partner", "Partner"),
                            ("public relations", "Public Relations"),
                            ("compaign", "Campaign"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "captcha_provider",
                    models.CharField(
                        blank=True,
                        choices=[("", "None"), ("turnstile", "Cloudflare Turnstile")],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "captcha_site_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "captcha_secret",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("reject_disposable_email", models.BooleanField(default=True)),
                (
                    "assign_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webforms_assigned",
                        to="common.profile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "legacy_api_setting",
                    models.OneToOneField(
                        blank=True,
                        help_text="Set by the backfill migration. Links a legacy web-to-lead API key to the form that now backs it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="web_form",
                        to="common.apisettings",
                    ),
                ),
                (
                    "notify_profiles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="webforms_notified",
                        to="common.profile",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="webforms", to="common.tags"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web form",
                "verbose_name_plural": "Web forms",
                "db_table": "web_form",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WebFormDailyStat",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateField()),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="webforms.webform",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web form daily stat",
                "verbose_name_plural": "Web form daily stats",
                "db_table": "web_form_daily_stat",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="WebFormField",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[("lead", "Lead field"), ("custom", "Custom field")],
                        max_length=16,
                    ),
                ),
                (
                    "lead_field",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("salutation", "Salutation"),
                            ("first_name", "First name"),
                            ("last_name", "Last name"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("company_name", "Company name"),
                            ("job_title", "Job title"),
                            ("website", "Website"),
                            ("title", "Subject"),
                            ("description", "Message"),
                            ("city", "City"),
                            ("state", "State"),
                            ("country", "Country"),
                            ("postcode", "Postal code"),
                            ("industry", "Industry"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(max_length=128)),
                (
                    "placeholder",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "custom_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webform_fields",
                        to="common.customfielddefinition",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="webforms.webform",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web form field",
                "verbose_name_plural": "Web form fields",
                "db_table": "web_form_field",
                "ordering": ("order", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="WebFormSubmission",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            (
                                "accepted_duplicate",
                                "Accepted, merged into an existing lead",
                            ),
                            ("rejected_spam", "Rejected as spam"),
                            ("rejected_invalid", "Rejected as invalid"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "reject_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("submitted_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("referer", models.CharField(blank=True, default="", max_length=512)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="webforms.webform",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webform_submissions",
                        to="leads.lead",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web form submission",
                "verbose_name_plural": "Web form submissions",
                "db_table": "web_form_submission",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="webform",
            index=models.Index(
                fields=["org", "-created_at"], name="web_form_org_id_2a78cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webformdailystat",
            index=models.Index(
                fields=["org", "-created_at"], name="web_form_da_org_id_a37749_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webformdailystat",
            index=models.Index(
                fields=["form", "-date"], name="web_form_da_form_id_06ce7d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="webformdailystat",
            constraint=models.UniqueConstraint(
                fields=("form", "date"), name="web_form_daily_stat_unique_day"
            ),
        ),
        migrations.AddIndex(
            model_name="webformfield",
            index=models.Index(
                fields=["org", "-created_at"], name="web_form_fi_org_id_8d0b72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webformfield",
            index=models.Index(
                fields=["form", "order"], name="web_form_fi_form_id_532236_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="webformfield",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lead_field", ""), _negated=True),
                fields=("form", "lead_field"),
                name="web_form_field_unique_lead_field",
            ),
        ),
        migrations.AddConstraint(
            model_name="webformfield",
            constraint=models.UniqueConstraint(
                condition=models.Q(("custom_field__isnull", False)),
                fields=("form", "custom_field"),
                name="web_form_field_unique_custom_field",
            ),
        ),
        migrations.AddConstraint(
            model_name="webformfield",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("custom_field__isnull", False), ("lead_field", "")),
                    models.Q(
                        models.Q(("lead_field", ""), _negated=True),
                        ("custom_field__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="web_form_field_exactly_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="webformsubmission",
            index=models.Index(
                fields=["org", "-created_at"], name="web_form_su_org_id_2c1d24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webformsubmission",
            index=models.Index(
                fields=["form", "-created_at"], name="web_form_su_form_id_d12f93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webformsubmission",
            index=models.Index(
                fields=["form", "status"], name="web_form_su_form_id_890953_idx"
            ),
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
    ]
