# Generated by Django 6.1.1 on 2026-09-26 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # The last committed cases migration. Only the Case table itself is
        # needed, and pinning to a tracked file keeps this independent of
        # cases migrations still in flight.
        ("cases", "0030_escalationpolicy_first_response_hours_and_more"),
        ("webforms", "0002_backfill_legacy_api_settings"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="webformfield",
            name="web_form_field_exactly_one_target",
        ),
        migrations.AddField(
            model_name="webform",
            name="target",
            field=models.CharField(
                choices=[("lead", "Lead"), ("ticket", "Ticket")],
                default="lead",
                help_text="What an accepted submission creates. Fixed once the form has submissions, so its history never mixes leads and tickets.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="webform",
            name="ticket_priority",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Normal", "Normal"),
                    ("High", "High"),
                    ("Urgent", "Urgent"),
                ],
                default="Normal",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="webform",
            name="ticket_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Question", "Question"),
                    ("Incident", "Incident"),
                    ("Problem", "Problem"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="webformfield",
            name="ticket_field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("first_name", "First name"),
                    ("last_name", "Last name"),
                    ("phone", "Phone"),
                    ("company_name", "Company name"),
                    ("name", "Subject"),
                    ("description", "Message"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="webformsubmission",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webform_submissions",
                to="cases.case",
            ),
        ),
        migrations.AlterField(
            model_name="webformfield",
            name="source",
            field=models.CharField(
                choices=[
                    ("lead", "Lead field"),
                    ("ticket", "Ticket field"),
                    ("custom", "Custom field"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="webformfield",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ticket_field", ""), _negated=True),
                fields=("form", "ticket_field"),
                name="web_form_field_unique_ticket_field",
            ),
        ),
        migrations.AddConstraint(
            model_name="webformfield",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("custom_field__isnull", False),
                        ("lead_field", ""),
                        ("ticket_field", ""),
                    ),
                    models.Q(
                        models.Q(("lead_field", ""), _negated=True),
                        ("custom_field__isnull", True),
                        ("ticket_field", ""),
                    ),
                    models.Q(
                        models.Q(("ticket_field", ""), _negated=True),
                        ("custom_field__isnull", True),
                        ("lead_field", ""),
                    ),
                    _connector="OR",
                ),
                name="web_form_field_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="webformsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lead__isnull", True), ("case__isnull", True), _connector="OR"
                ),
                name="web_form_submission_lead_or_case",
            ),
        ),
    ]
