from rest_framework import serializers

from webhooks import events, ssrf
from webhooks.models import WebhookDelivery, WebhookEndpoint


class WebhookEndpointSerializer(serializers.ModelSerializer):
    """An endpoint as an admin sees it. The secret is only ever a hint here;
    the create and rotate views add the full value to their own response."""

    secret_hint = serializers.CharField(read_only=True)

    class Meta:
        model = WebhookEndpoint
        fields = (
            "id",
            "url",
            "description",
            "events",
            "format",
            "is_active",
            "disabled_reason",
            "secret_hint",
            "created_at",
            "updated_at",
        )
        read_only_fields = ("id", "disabled_reason", "created_at", "updated_at")

    def validate(self, attrs):
        # The secret is minted by the server. Refused loudly rather than
        # dropped, so a caller who thinks they chose one learns they did not.
        if "secret" in self.initial_data:
            raise serializers.ValidationError(
                {"secret": "The signing secret is generated by the server."}
            )
        return attrs

    def validate_url(self, value):
        value = value.strip()
        try:
            ssrf.validate_url(value)
        except ssrf.UnsafeDestination as exc:
            raise serializers.ValidationError(str(exc)) from None
        return value

    def validate_description(self, value):
        return value.strip()

    def validate_events(self, value):
        if not isinstance(value, list) or not value:
            raise serializers.ValidationError("Choose at least one event.")
        unknown = [
            v for v in value if not isinstance(v, str) or v not in events.EVENT_NAMES
        ]
        if unknown:
            raise serializers.ValidationError(
                f"Unknown event: {', '.join(str(v) for v in unknown[:5])}."
            )
        # Catalogue order, each once.
        return [name for name in events.EVENT_NAMES if name in value]

    def update(self, instance, validated_data):
        # Turning an endpoint back on clears the reason it was turned off.
        if validated_data.get("is_active") and not instance.is_active:
            instance.disabled_reason = ""
        return super().update(instance, validated_data)


class WebhookDeliverySerializer(serializers.ModelSerializer):
    class Meta:
        model = WebhookDelivery
        fields = (
            "id",
            "endpoint",
            "event",
            "event_id",
            "status",
            "attempts",
            "response_status",
            "error",
            "next_attempt_at",
            "last_attempt_at",
            "created_at",
            "payload",
        )
        read_only_fields = fields
