# Generated by Django 6.0.7 on 2026-08-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0015_drop_orphan_deal_pipeline_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesgoal",
            name="type_weights",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Optional multiplier per opportunity type, e.g. {"RENEWAL": 0.5, "NEW_BUSINESS": 1.5}. A type left out of the map, and a deal with no type at all, counts at its full value. An empty map is an unweighted goal. Not accepted on an ACTIVITIES goal, which has no deal type to weigh.',
                verbose_name="Deal Type Weights",
            ),
        ),
        migrations.AlterField(
            model_name="salesgoal",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("REVENUE", "Revenue"),
                    ("DEALS_CLOSED", "Deals Closed"),
                    ("ACTIVITIES", "Activities"),
                ],
                max_length=20,
                verbose_name="Goal Type",
            ),
        ),
    ]
