# Generated by Django 6.1.1 on 2026-09-26 01:34

"""Invoice and estimate numbers become unique per org instead of globally.

Each org numbers its own documents (INV-<date>-0001 and up), and under RLS the
generator can only see its own org's rows, so two orgs minted the same number
and the second save failed on the global unique. Existing rows were globally
unique, so they are unique per org too, and the new constraint cannot fail on
production data. Forward drops the single-column unique (and its _like index)
and adds UNIQUE (org_id, number). Reversible, but reversing fails once two orgs
share a number, which is exactly what this migration allows.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "invoices",
            "0010_estimate_accepted_by_email_estimate_accepted_by_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimate",
            name="estimate_number",
            field=models.CharField(max_length=50, verbose_name="Estimate Number"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=50, verbose_name="Invoice Number"),
        ),
        migrations.AddConstraint(
            model_name="estimate",
            constraint=models.UniqueConstraint(
                fields=("org", "estimate_number"), name="unique_estimate_number_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("org", "invoice_number"), name="unique_invoice_number_per_org"
            ),
        ),
    ]
