# Generated by Django 6.0.7 on 2026-08-15 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0037_org_timezone"),
        ("contacts", "0013_contact_is_sample"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="commented_by_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portal_comments",
                to="contacts.contact",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("commented_by__isnull", True),
                    ("commented_by_contact__isnull", True),
                    _connector="OR",
                ),
                name="comment_single_author",
            ),
        ),
    ]
