# Generated by Django 6.0.7 on 2026-08-15 16:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0038_comment_body_and_contact_author"),
        ("contacts", "0013_contact_is_sample"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalLoginToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("code_hash", models.CharField(max_length=256)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contacts.contact",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.org"
                    ),
                ),
            ],
            options={
                "db_table": "portal_login_token",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["contact", "created_at"],
                        name="portal_logi_contact_403e11_idx",
                    )
                ],
            },
        ),
    ]
