# Generated by Django 6.0.7 on 2026-08-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0039_portal_login_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(max_length=10000),
        ),
    ]
