# Generated by Django 6.1.1 on 2026-09-26 07:34

import django.db.models.functions.text
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0042_recompute_tag_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="help_center_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="org",
            name="help_center_slug",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[common.validators.validate_help_center_slug],
            ),
        ),
        migrations.AddConstraint(
            model_name="org",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("help_center_slug"),
                name="org_help_center_slug_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="org",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("help_center_enabled", False),
                    ("help_center_slug__isnull", False),
                    _connector="OR",
                ),
                name="org_help_center_enabled_needs_slug",
            ),
        ),
    ]
