# Generated by Django 6.0.7 on 2026-08-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0028_inboundmailbox_webhook_secret_help_text"),
        ("common", "0040_comment_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="solution_tags", to="common.tags"
            ),
        ),
    ]
