# Generated by Django 6.0.7 on 2026-08-16 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0029_solution_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="escalationpolicy",
            name="first_response_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Target hours for first response. Blank uses the built-in default.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8760),
                ],
            ),
        ),
        migrations.AddField(
            model_name="escalationpolicy",
            name="resolution_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Target hours for resolution. Blank uses the built-in default.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8760),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="sla_first_response_hours",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Target hours for first response",
                null=True,
                verbose_name="First Response SLA (hours)",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="sla_resolution_hours",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Target hours for resolution",
                null=True,
                verbose_name="Resolution SLA (hours)",
            ),
        ),
    ]
